name = "TinyBlog"
description = "Light and simple blog theme"
license = "MIT"
homepage = "https://github.com/tinyops-ru/tinyblog-zola-theme"
min_version = "0.4.1"
demo = "https://b.tinyops.ru"

taxonomies = [
 {name = "tags", rss = true},
 {name = "categories", paginate_by = 5, rss = true},  # 5 items per page for a term
 {name = "authors"} # Basic definition: no RSS or pagination
]

[author]
name = "Eugene Lebedev"
homepage = "https://tinyops.ru"
