name = "TinyBlog"
description = "Light and simple blog theme"
license = "MIT"
homepage = "https://github.com/lebe-dev/tinyblog-zola-theme"
min_version = "0.4.1"
demo = "https://github.com/lebe-dev"

[author]
name = "Eugene Lebedev"
homepage = "https://tinyops.ru"
